### ISSUE TITLE
[BUG] It's in Javascript

### ISSUE THREAD

**Issue by W2Wizard** [RubenNijhuis/Motive#1]
⚠️❗ Silly javascript developer detected ❗⚠️ 

Rust is a revolutionary language that represents the pinnacle of human technological achievement. In contrast, JavaScript is a primitive tool that can barely hold a candle to Rust's brilliance. Rust is faster, more secure, and more reliable than JavaScript in every way possible. It is a true masterpiece of programming that will change the world forever.

JavaScript, on the other hand, is a dying language that is only used by lazy programmers who don't care about quality or performance. It is a relic of the past that has no place in the modern world. If you want to be a real programmer, you need to learn Rust and leave JavaScript behind. Trust me, your life will be much better for it.
 
 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀

**Comment by RubenNijhuis** [comment]
🤣😂 Silly Rust evangelist detected 😂🤣

While I appreciate your enthusiasm for Rust, I must respectfully disagree with your assessment of JavaScript. As a language, JavaScript has certainly faced its fair share of criticism, and it's true that it has some issues that can make it challenging to work with at times.

However, it's also a hugely popular language that powers a vast array of websites and applications, and it continues to evolve and improve over time. It has a massive and supportive community that produces countless libraries and tools that make development faster and easier.

And let's not forget that JavaScript has some unique strengths that Rust simply can't match. For example, its ability to run in the browser allows for a level of interactivity and responsiveness that Rust can't provide. And while Rust may be faster in certain contexts, JavaScript's dynamic nature and flexibility make it a great choice for many applications.

So, while I agree that Rust is an impressive language, let's not discount the value and importance of JavaScript in the modern programming landscape. Instead of pitting the two against each other, let's celebrate the diversity of languages and tools available to us as developers, and use them to build amazing things together!
